services:
  php:
    build:
      context: .
      dockerfile: /dockerfiles/php.Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - test_only_network
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_only
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - test_only_network
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - test_only_network
networks:
  test_only_network:
volumes:
  mysql_data: